language: emacs-lisp
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-elisp/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq -yy ${EMACS}

env:
  - EMACS=emacs24
  - EMACS=emacs-snapshot

script:
  - emacs --version
  - make test

notifications:
  email: false
